### ISSUE TITLE
Django 1.9 incompatibilities

### ISSUE THREAD

**Issue by debnet** [jazzband/django-configurations#133]
```
"C:\Program Files (x86)\PyCharm\bin\runnerw.exe" D:\VirtualEnvs\nouvelleoffre\Scripts\python.exe D:/Git/nouvelleoffre-back/manage.py runserver 8000
Traceback (most recent call last):
  File "D:/Git/nouvelleoffre-back/manage.py", line 10, in <module>
    execute_from_command_line(sys.argv)
  File "D:\VirtualEnvs\nouvelleoffre\lib\site-packages\django\core\management\__init__.py", line 351, in execute_from_command_line
    utility.execute()
  File "D:\VirtualEnvs\nouvelleoffre\lib\site-packages\django\core\management\__init__.py", line 343, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "D:\VirtualEnvs\nouvelleoffre\lib\site-packages\django\core\management\__init__.py", line 177, in fetch_command
    commands = get_commands()
  File "C:\Python34\lib\functools.py", line 448, in wrapper
    result = user_function(*args, **kwds)
  File "D:\VirtualEnvs\nouvelleoffre\lib\site-packages\django\core\management\__init__.py", line 72, in get_commands
    for app_config in reversed(list(apps.get_app_configs())):
  File "D:\VirtualEnvs\nouvelleoffre\lib\site-packages\django\apps\registry.py", line 137, in get_app_configs
    self.check_apps_ready()
  File "D:\VirtualEnvs\nouvelleoffre\lib\site-packages\django\apps\registry.py", line 124, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

Could happen depending of applications in INSTALLED_APPS, for example `drfdocs==0.0.5` with `django-configurations#master`.

**Comment by bittner** [comment]
Is this still relevant with Django 1.11 and 2.x?

**Comment by blueyed** [comment]
Closing for now.
