### ISSUE TITLE
Support for Django 1.10.2

### ISSUE THREAD

**Issue by AbsolutRed** [jazzband/django-configurations#163]
After upgrading to the above version for Django, I've been getting the following errors:

```
Traceback (most recent call last):
  File "manage.py", line 28, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/Absolut_Red/virtualenvs/phase2/lib/python3.4/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/Absolut_Red/virtualenvs/phase2/lib/python3.4/site-packages/django/core/management/__init__.py", line 341, in execute
    django.setup()
  File "/Users/Absolut_Red/virtualenvs/phase2/lib/python3.4/site-packages/django/__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/Users/Absolut_Red/virtualenvs/phase2/lib/python3.4/site-packages/django/apps/registry.py", line 78, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant 
```
The exact same setup works for Django 1.8.14. Is this a WIP? Appreciate your time!

**Comment by blueyed** [comment]
2.0 works for us on Django 1.10.2, so it might be something special in your setup?!

**Comment by AbsolutRed** [comment]
Celery ended up being the troublemaker. Upgrading celery and its dependencies did the trick!
