### ISSUE TITLE
Django server not starting in docker - WSGI configuration issue?

### ISSUE THREAD

**Issue by fronbasal** [jazzband/django-configurations#198]
Hello
I am experiencing an issue with django-configurations when trying to start the dev server in my docker environment. When attempting to start the server (`./manage.py runserver 0.0.0.0:8000`) it throws the following traceback:

```
django-configurations version 2.0, using configuration 'Staging'
Performing system checks...

System check identified no issues (0 silenced).
June 21, 2018 - 11:43:19
Django version 2.0, using settings 'application.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x7f2694c1a158>
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/django/utils/autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 140, in inner_run
    handler = self.get_handler(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/contrib/staticfiles/management/commands/runserver.py", line 27, in get_handler
    handler = super().get_handler(*args, **options)
  File "/usr/local/lib/python3.6/site-packages/django/core/management/commands/runserver.py", line 65, in get_handler
    return get_internal_wsgi_application()
  File "/usr/local/lib/python3.6/site-packages/django/core/servers/basehttp.py", line 44, in get_internal_wsgi_application
    return import_string(app_path)
  File "/usr/local/lib/python3.6/site-packages/django/utils/module_loading.py", line 17, in import_string
    module = import_module(module_path)
  File "/usr/local/lib/python3.6/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 678, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/app/application/wsgi.py", line 12, in <module>
    from configurations.wsgi import get_wsgi_application
  File "/usr/local/lib/python3.6/site-packages/configurations/wsgi.py", line 14, in <module>
    application = get_wsgi_application()
  File "/usr/local/lib/python3.6/site-packages/django/core/wsgi.py", line 13, in get_wsgi_application
    return WSGIHandler()
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/wsgi.py", line 140, in __init__
    self.load_middleware()
  File "/usr/local/lib/python3.6/site-packages/django/core/handlers/base.py", line 39, in load_middleware
    mw_instance = middleware(handler)
TypeError: __init__() takes 1 positional argument but 2 were given

```

My wsgi.py file:

```python
import os

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'application.settings')
os.environ.setdefault('DJANGO_CONFIGURATION', 'Staging')

from configurations.wsgi import get_wsgi_application

application = get_wsgi_application()

```

If you need further information, please ask.
Thank you very much!

**Comment by fronbasal** [comment]
Realized that this issue is middleware related. Sorry.
