### ISSUE TITLE
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty

### ISSUE THREAD

**Issue by KrunchMuffin** [jazzband/django-configurations#214]
I don't know what I am doing wrong. I followed the instructions...

>  raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
 django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty. 

```
Traceback (most recent call last):
  File "C:/Users/Derek/PycharmProjects/S101Admin/manage.py", line 17, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Derek\.virtualenvs\virtual_env\S101Admin\lib\site-packages\django\core\management\__init__.py", line 381, in execute_from_command_line
    utility.execute()
  File "C:\Users\Derek\.virtualenvs\virtual_env\S101Admin\lib\site-packages\django\core\management\__init__.py", line 375, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Derek\.virtualenvs\virtual_env\S101Admin\lib\site-packages\django\core\management\base.py", line 316, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Derek\.virtualenvs\virtual_env\S101Admin\lib\site-packages\django\core\management\commands\runserver.py", line 60, in execute
    super().execute(*args, **options)
  File "C:\Users\Derek\.virtualenvs\virtual_env\S101Admin\lib\site-packages\django\core\management\base.py", line 353, in execute
    output = self.handle(*args, **options)
  File "C:\Users\Derek\.virtualenvs\virtual_env\S101Admin\lib\site-packages\django\core\management\commands\runserver.py", line 67, in handle
    if not settings.DEBUG and not settings.ALLOWED_HOSTS:
  File "C:\Users\Derek\.virtualenvs\virtual_env\S101Admin\lib\site-packages\django\conf\__init__.py", line 57, in __getattr__
    self._setup(name)
  File "C:\Users\Derek\.virtualenvs\virtual_env\S101Admin\lib\site-packages\django\conf\__init__.py", line 44, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\Derek\.virtualenvs\virtual_env\S101Admin\lib\site-packages\django\conf\__init__.py", line 126, in __init__
    raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
```

**settings.py**

```
import os

from functions.utils import djsettings
from configurations import Configuration


class Dev(Configuration):
    DEBUG = True


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

SECRET_KEY = djsettings.get('django_secret_key')

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'bootstrap_admin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'S101.apps.S101Config',
    'crispy_forms',

    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',

    'usership',
    'pages',
    'accountmgmt',
    # 'functions',
    # 'settings',
]
if DEBUG:
    INSTALLED_APPS += ['debug_toolbar']

AUTH_USER_MODEL = 'usership.CustomUser'
MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'debug_toolbar.middleware.DebugToolbarMiddleware',
]

ROOT_URLCONF = 'S101Admin.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'S101Admin.wsgi.application'
INTERNAL_IPS = ('127.0.0.1',)

DATABASES = {
    'default': {
        'ENGINE': 'sql_server.pyodbc',
        'NAME': djsettings.get('db_name'),
        'USER': djsettings.get('db_user'),
        'PASSWORD': djsettings.get('db_password'),
        'HOST': djsettings.get('db_host'),
        'PORT': '',
        'OPTIONS': {
            'driver': 'ODBC Driver 17 for SQL Server',
            'unicode_results': True,
        }
    }
}

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

STATIC_URL = '/static/'

STATICFILES_DIRS = (
    os.path.join(BASE_DIR, 'static'),
)

LOGIN_REDIRECT_URL = 'home'
LOGOUT_REDIRECT_URL = 'home'

AUTHENTICATION_BACKENDS = (
    "django.contrib.auth.backends.ModelBackend",
    "allauth.account.auth_backends.AuthenticationBackend",
)

SITE_ID = 1

ACCOUNT_EMAIL_REQUIRED = True
ACCOUNT_USERNAME_REQUIRED = False

CRISPY_TEMPLATE_PACK = 'bootstrap4'
```

**Comment by bittner** [comment]
> I don't know what I am doing wrong.

Nothing, apart from not providing a `DJANGO_SECRET_KEY` environment variable. If this issue is about your development environment you can fix the error by creating an `.env` file in your project root and [configure Configurations  to read that file](https://django-configurations.readthedocs.io/en/latest/cookbook/#read-env-file).

You must provide a secret key for Django in your application environment. This is [not explicitly mentioned](https://django-configurations.readthedocs.io/en/latest/values/#configurations.values.SecretValue) in the docs, because Django itself complains (not `django-configurations`).

If you feel this is not clear and worth mentioning in the documentation feel free to enhance the docs via a PR.

**Comment by KrunchMuffin** [comment]
This was a long time ago and have since moved on from it. at any rate, the secret was there as referenced by `SECRET_KEY = djsettings.get('django_secret_key')` and it was in place. If it were that easy, I would not have posted.

**Comment by bittner** [comment]
Aha, but that's another problem: You tried to set the `SECRET_KEY` in Django's settings module directly. With Configurations it should be class-based, see [the documentation](https://django-configurations.readthedocs.io/en/latest/patterns/#server-specific-settings) for reference. Example:

```python
from configurations import Configuration

class Base(Configuration):
    SECRET_KEY = values.SecretValue()
```

**Comment by KrunchMuffin** [comment]
ok, thanks. I was more n00bish 30 days ago. 😆
