### ISSUE TITLE
Tests are failing

### ISSUE THREAD

**Issue by fabaff** [jazzband/django-configurations#249]
In a `venv` with django-3.0.1 and Python 3.7.5 are the tests failing.

```bash
(django-configurations) [fab@abc3 django-configurations]$ export DJANGO_CONFIGURATION="Test"
(django-configurations) [fab@abc3 django-configurations]$ export DJANGO_SETTINGS_MODULE="tests.settings.main"
(django-configurations) [fab@abc3 django-configurations]$ python3 setup.py test
running test
running egg_info
writing django_configurations.egg-info/PKG-INFO
writing dependency_links to django_configurations.egg-info/dependency_links.txt
writing entry points to django_configurations.egg-info/entry_points.txt
writing requirements to django_configurations.egg-info/requires.txt
writing top-level names to django_configurations.egg-info/top_level.txt
reading manifest template 'MANIFEST.in'
writing manifest file 'django_configurations.egg-info/SOURCES.txt'
running build_ext
setup_1
setup_2
setup_done
Traceback (most recent call last):
  File "setup.py", line 61, in <module>
    zip_safe=False,
  File "/home/fab/Documents/repos/django-configurations/lib64/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib64/python3.7/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib64/python3.7/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib64/python3.7/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/home/fab/Documents/repos/django-configurations/lib64/python3.7/site-packages/setuptools/command/test.py", line 229, in run
    self.run_tests()
  File "/home/fab/Documents/repos/django-configurations/lib64/python3.7/site-packages/setuptools/command/test.py", line 251, in run_tests
    exit=False,
  File "/usr/lib64/python3.7/unittest/main.py", line 100, in __init__
    self.parseArgs(argv)
  File "/usr/lib64/python3.7/unittest/main.py", line 124, in parseArgs
    self._do_discovery(argv[2:])
  File "/usr/lib64/python3.7/unittest/main.py", line 244, in _do_discovery
    self.createTests(from_discovery=True, Loader=Loader)
  File "/usr/lib64/python3.7/unittest/main.py", line 154, in createTests
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/usr/lib64/python3.7/unittest/loader.py", line 349, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/usr/lib64/python3.7/unittest/loader.py", line 406, in _find_tests
    full_path, pattern, namespace)
  File "/usr/lib64/python3.7/unittest/loader.py", line 483, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/home/fab/Documents/repos/django-configurations/lib64/python3.7/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python3.7/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/fab/Documents/repos/django-configurations/lib64/python3.7/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python3.7/unittest/loader.py", line 191, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/home/fab/Documents/repos/django-configurations/lib64/python3.7/site-packages/setuptools/command/test.py", line 55, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/usr/lib64/python3.7/unittest/loader.py", line 154, in loadTestsFromName
    module = __import__(module_name)
  File "/home/fab/Documents/repos/django-configurations/tests/management/commands/old_optparse_command.py", line 5, in <module>
    class Command(BaseCommand):
  File "/home/fab/Documents/repos/django-configurations/tests/management/commands/old_optparse_command.py", line 11, in Command
    option_list = BaseCommand.option_list + (
AttributeError: type object 'BaseCommand' has no attribute 'option_list'
```

**Comment by kloczek** [comment]
Looks like pytest is failing as well
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-django-configurations-2.2-9.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-django-configurations-2.2-9.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra --import-mode=importlib
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.12, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
benchmark: 3.4.1 (defaults: timer=time.perf_counter disable_gc=False min_rounds=5 min_time=0.000005 max_time=1.0 calibration_precision=10 warmup=False warmup_iterations=100000)
Using --randomly-seed=2781524819
rootdir: /home/tkloczko/rpmbuild/BUILD/django-configurations-2.2
plugins: forked-1.3.0, shutil-1.7.0, virtualenv-1.7.0, expect-1.1.0, flake8-1.0.7, timeout-1.4.2, betamax-0.8.1, freezegun-0.4.2, aspectlib-1.5.2, toolbox-0.5, rerunfailures-9.1.1, requests-mock-1.9.3, cov-2.12.1, flaky-3.7.0, benchmark-3.4.1, xdist-2.3.0, pylama-7.7.1, datadir-1.3.1, regressions-2.2.0, xprocess-0.18.1, black-0.3.12, asyncio-0.15.1, subtests-0.5.0, isort-2.0.0, hypothesis-6.14.6, mock-3.6.1, profiling-1.7.0, randomly-3.8.0, nose2pytest-1.0.8, pyfakefs-4.5.1, tornado-0.8.1, twisted-1.13.3, aiohttp-0.3.0, localserver-0.5.0, anyio-3.3.1, trio-0.7.0, Faker-8.12.2, cases-3.6.4, yagot-0.5.0
collected 68 items / 2 errors / 66 selected

================================================================================== ERRORS ==================================================================================
___________________________________________________________________ ERROR collecting tests/setup_test.py ___________________________________________________________________
tests/setup_test.py:11: in <module>
    configurations.setup()
../../BUILDROOT/python-django-configurations-2.2-9.fc35.x86_64/usr/lib/python3.8/site-packages/configurations/__init__.py:31: in setup
    _setup()
../../BUILDROOT/python-django-configurations-2.2-9.fc35.x86_64/usr/lib/python3.8/site-packages/configurations/__init__.py:12: in _setup
    importer.install()
../../BUILDROOT/python-django-configurations-2.2-9.fc35.x86_64/usr/lib/python3.8/site-packages/configurations/importer.py:49: in install
    importer = ConfigurationImporter(check_options=check_options)
../../BUILDROOT/python-django-configurations-2.2-9.fc35.x86_64/usr/lib/python3.8/site-packages/configurations/importer.py:68: in __init__
    self.validate()
../../BUILDROOT/python-django-configurations-2.2-9.fc35.x86_64/usr/lib/python3.8/site-packages/configurations/importer.py:113: in validate
    raise ImproperlyConfigured(self.error_msg.format(self.modvar))
E   django.core.exceptions.ImproperlyConfigured: Configuration cannot be imported, environment variable DJANGO_SETTINGS_MODULE is undefined.
----------------------------------------------------------------------------- Captured stdout ------------------------------------------------------------------------------
setup_1
__________________________________________________________________ ERROR collecting tests/test_sphinx.py ___________________________________________________________________
tests/test_sphinx.py:9: in <module>
    class SphinxTests(TestCase):
tests/test_sphinx.py:10: in SphinxTests
    docs_dir = os.path.join(settings.BASE_DIR, 'docs')
/usr/lib/python3.8/site-packages/django/conf/__init__.py:82: in __getattr__
    self._setup(name)
/usr/lib/python3.8/site-packages/django/conf/__init__.py:63: in _setup
    raise ImproperlyConfigured(
E   django.core.exceptions.ImproperlyConfigured: Requested setting BASE_DIR, but settings are not configured. You must either define the environment variable DJANGO_SETTINGS_MODULE or call settings.configure() before accessing settings.
========================================================================= short test summary info ==========================================================================
ERROR tests/setup_test.py - django.core.exceptions.ImproperlyConfigured: Configuration cannot be imported, environment variable DJANGO_SETTINGS_MODULE is undefined.
ERROR tests/test_sphinx.py - django.core.exceptions.ImproperlyConfigured: Requested setting BASE_DIR, but settings are not configured. You must either define the environ...
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 2 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================ 2 errors in 0.76s =============================================================================
pytest-xprocess reminder::Be sure to terminate the started process by running 'pytest --xkill' if you have not explicitly done so in your fixture with 'xprocess.getinfo(<process_name>).terminate()'.
```
