### ISSUE TITLE
populate() isn't reentrant

### ISSUE THREAD

**Issue by eduzen** [jazzband/django-configurations#255]
I'm trying to use django-configurations for the first time with a project of django 3.0.5 and only one app. And for every command with manage.py triggers:
```
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 401, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.7/site-packages/django/core/management/__init__.py", line 377, in execute
    django.setup()
  File "/usr/local/lib/python3.7/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/usr/local/lib/python3.7/site-packages/django/apps/registry.py", line 83, in populate
    raise RuntimeError("populate() isn't reentrant")
RuntimeError: populate() isn't reentrant
```

My config is:

```
import os
from boto3.session import Session
from configurations import Configuration


class Base(Configuration):
    SECRET_KEY = os.getenv("SECRET_KEY")
    BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    LANGUAGE_CODE = "en-us"
    TIME_ZONE = "Europe/London"
    USE_I18N = True
    USE_L10N = True
    USE_TZ = True
    APPEND_SLASH = True
    LOGIN_REDIRECT_URL = "home"
    ALLOWED_HOSTS = ["*"]

    # Application definition

    INSTALLED_APPS = [
        "django.contrib.admin",
        "django.contrib.auth",
        "django.contrib.contenttypes",
        "django.contrib.sessions",
        "django.contrib.messages",
        "django.contrib.staticfiles",
        "django_extensions",
        "django_celery_beat",
        "rest_framework",
        "crispy_forms",
        "reports",
    ]
```

If I comment the `# "reports",` works. I'm doing something wrong?

```
#!/usr/bin/env python
"""Django's command-line utility for administrative tasks."""
import os
import sys


def main():
    os.environ.setdefault("DJANGO_SETTINGS_MODULE", "roble.settings")
    os.environ.setdefault('DJANGO_CONFIGURATION', 'Base')
    try:
        from configurations.management import execute_from_command_line
    except ImportError as exc:
        raise ImportError(
            "Couldn't import Django. Are you sure it's installed and "
            "available on your PYTHONPATH environment variable? Did you "
            "forget to activate a virtual environment?"
        ) from exc
    execute_from_command_line(sys.argv)


if __name__ == "__main__":
    main()
```

**Comment by eduzen** [comment]
I had some problems with my app and I could see them without django-configurations, now they are fixed and configurations works. I'm closing the issue.
