### ISSUE TITLE
2.2: sphinx warnings

### ISSUE THREAD

**Issue by kloczek** [jazzband/django-configurations#293]
Yeah .. in source tree is `configurations/` disrectory and code is looking for `django-configurations/`
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.2.0

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 328, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/django-configurations-2.2/docs/conf.py", line 54, in <module>
    release = get_distribution("django-configurations").version
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 466, in get_distribution
    dist = get_provider(dist)
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 342, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 886, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/lib/python3.8/site-packages/pkg_resources/__init__.py", line 772, in resolve
    raise DistributionNotFound(req, requirers)
pkg_resources.DistributionNotFound: The 'django-configurations' distribution was not found and is required by the application
```

**Comment by kloczek** [comment]
No sorry .. issue is somewhere else. before `build_sphinx` needs to be generated `egg_info`
Nevertheless after that sphinx shows some warnings
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.2.0
making output directory... done
loading intersphinx inventory from http://docs.python.org/2.7/objects.inv...
loading intersphinx inventory from http://sphinx.pocoo.org/objects.inv...
loading intersphinx inventory from http://docs.djangoproject.com/en/dev/_objects/...
WARNING: failed to reach any of the inventories with the following issues:
intersphinx inventory 'http://sphinx.pocoo.org/objects.inv' not fetchable due to <class 'requests.exceptions.HTTPError'>: 400 Client Error: Bad Request for url: http://sphinx.pocoo.org/objects.inv
intersphinx inventory has moved: http://docs.python.org/2.7/objects.inv -> https://docs.python.org/2.7/objects.inv
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 5 added, 0 changed, 0 removed
reading sources... [100%] values
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-django-configurations.3 { patterns values cookbook changes } done
build succeeded, 1 warning.
```

**Comment by kloczek** [comment]
Just testted new version and all looks clean now.
Thank you :)
```console
+ /usr/bin/python3 setup.py build_sphinx -b man --build-dir build/sphinx
running build_sphinx
Running Sphinx v4.2.0
making output directory... done
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://www.sphinx-doc.org/en/master/objects.inv...
loading intersphinx inventory from https://docs.djangoproject.com/en/dev/_objects/...
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 5 added, 0 changed, 0 removed
reading sources... [100%] values
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-django-configurations.3 { patterns values cookbook changes } done
build succeeded.
```
