### ISSUE TITLE
django-configuration fails for SecretValue() in Production, while using Local class 

### ISSUE THREAD

**Issue by theskumar** [jazzband/django-configurations#96]
So the latest version of django-configurations tries to setup all the values all the sub-classes.

So if you have a setup like this:

```
class Common(Configuration):
  VALUE1 = values.Value()

class Local(Common):
  ...

class Production(Common):
  MY_VALUE = values.SecretValue()
```

and with `DJANGO_CONFIGURATION = Local`

I get the error, 

```
ValueError: Secret value u'MY_VALUE' is not set
```

The issue is not present in 0.8.0, but in latest code.

**Comment by wengole** [comment]
+1

I believe I am also getting this whilst trying to use Celery.

Here is my celery.py

```
from __future__ import absolute_import

import os

from celery import Celery
from django.conf import settings

os.environ.setdefault('DJANGO_SETTINGS_MODULE', 'wizfs.settings')
os.environ.setdefault('DJANGO_CONFIGURATION', 'ServerDebug')

from configurations import importer

importer.install()

app = Celery('wizfs')
app.config_from_object('django.conf:settings')
app.autodiscover_tasks(lambda: settings.INSTALLED_APPS)


@app.task(bind=True)
def debug_task(self):
    print('Request: {0!r}'.format(self.request))
```

and the settings.py

```
import os

from configurations import Configuration, values

BASE_DIR = os.path.dirname(os.path.dirname(__file__))


class Common(Configuration):
    BASE_DIR = os.path.dirname(os.path.dirname(__file__))
    SECRET_KEY = 'A KEY'
...
    CELERY_RESULT_BACKEND = 'redis://localhost:6379/0'
    CELERY_ACCEPT_CONTENT = ['pickle', ]
    CRISPY_TEMPLATE_PACK = 'bootstrap3'
...

class ServerDebug(Common):
    """
    Development config to be run on server
    """
    SECRET_KEY = values.SecretValue()
    DEFAULT_FROM_EMAIL = values.Value(
        'WiZFS <another@example.com>'
    )
    EMAIL_HOST = values.Value('localhost')
    EMAIL_PORT = values.IntegerValue(25)
    EMAIL_HOST_USER = values.SecretValue()
    EMAIL_HOST_PASSWORD = values.SecretValue()
    EMAIL_SUBJECT_PREFIX = values.Value('[WiZFS] ')
```

I am starting Celery as a systemd service

```
[Unit]
Description=An asynchronous task queue/job queue based on distributed message passing
After=redis.service

[Service]
User=me
Environment=DJANGO_SETTINGS_MODULE=wizfs.settings
Environment=DJANGO_CONFIGURATION=ServerDebug
Environment=DJANGO_SECRET_KEY=SomeOtherKey
Environment=DJANGO_EMAIL_HOST=host.mail.com
Environment=DJANGO_EMAIL_USER=username
Environment=DJANGO_EMAIL_PASSWORD=password
ExecStart=/home/ben/PycharmProjects/wizfs/bin/celery -A wizfs worker -l warn -C --autoreload

[Install]
WantedBy=multi-user.target
```

and everytime I try to start it I get:

```
Mar 02 12:18:58 san systemd[1]: Starting An asynchronous task queue/job queue based on distributed message passing...
Mar 02 12:18:58 san systemd[1]: Started An asynchronous task queue/job queue based on distributed message passing.
Mar 02 12:18:58 san celery[12104]: Traceback (most recent call last):
Mar 02 12:18:58 san celery[12104]: File "/home/ben/PycharmProjects/wizfs/bin/celery", line 48, in <module>
Mar 02 12:18:58 san celery[12104]: sys.exit(celery.__main__.main())
Mar 02 12:18:58 san celery[12104]: File "/home/ben/PycharmProjects/wizfs/eggs/celery-3.1.17-py2.7.egg/celery/__main__.py", line 30, in main
Mar 02 12:18:58 san celery[12104]: main()
Mar 02 12:18:58 san celery[12104]: File "/home/ben/PycharmProjects/wizfs/eggs/celery-3.1.17-py2.7.egg/celery/bin/celery.py", line 81, in main
Mar 02 12:18:58 san celery[12104]: cmd.execute_from_commandline(argv)
Mar 02 12:18:58 san celery[12104]: File "/home/ben/PycharmProjects/wizfs/eggs/celery-3.1.17-py2.7.egg/celery/bin/celery.py", line 769, in execute_from_commandline
Mar 02 12:18:58 san celery[12104]: super(CeleryCommand, self).execute_from_commandline(argv)))
Mar 02 12:18:58 san celery[12104]: File "/home/ben/PycharmProjects/wizfs/eggs/celery-3.1.17-py2.7.egg/celery/bin/base.py", line 307, in execute_from_commandline
Mar 02 12:18:58 san celery[12104]: return self.handle_argv(self.prog_name, argv[1:])
Mar 02 12:18:58 san celery[12104]: File "/home/ben/PycharmProjects/wizfs/eggs/celery-3.1.17-py2.7.egg/celery/bin/celery.py", line 761, in handle_argv
Mar 02 12:18:58 san celery[12104]: return self.execute(command, argv)
Mar 02 12:18:58 san celery[12104]: File "/home/ben/PycharmProjects/wizfs/eggs/celery-3.1.17-py2.7.egg/celery/bin/celery.py", line 693, in execute
Mar 02 12:18:58 san celery[12104]: ).run_from_argv(self.prog_name, argv[1:], command=argv[0])
Mar 02 12:18:58 san celery[12104]: File "/home/ben/PycharmProjects/wizfs/eggs/celery-3.1.17-py2.7.egg/celery/bin/worker.py", line 177, in run_from_argv
Mar 02 12:18:58 san celery[12104]: *self.parse_options(prog_name, argv, command))
Mar 02 12:18:58 san celery[12104]: File "/home/ben/PycharmProjects/wizfs/eggs/celery-3.1.17-py2.7.egg/celery/bin/base.py", line 407, in parse_options
Mar 02 12:18:58 san celery[12104]: self.parser = self.create_parser(prog_name, command)
Mar 02 12:18:58 san celery[12104]: File "/home/ben/PycharmProjects/wizfs/eggs/celery-3.1.17-py2.7.egg/celery/bin/base.py", line 413, in create_parser
Mar 02 12:18:58 san celery[12104]: self.get_options() +
Mar 02 12:18:58 san celery[12104]: File "/home/ben/PycharmProjects/wizfs/eggs/celery-3.1.17-py2.7.egg/celery/bin/worker.py", line 221, in get_options
Mar 02 12:18:58 san celery[12104]: conf = self.app.conf
Mar 02 12:18:58 san celery[12104]: File "/home/ben/PycharmProjects/wizfs/eggs/kombu-3.0.24-py2.7.egg/kombu/utils/__init__.py", line 322, in __get__
Mar 02 12:18:58 san celery[12104]: value = obj.__dict__[self.__name__] = self.__get(obj)
Mar 02 12:18:58 san celery[12104]: File "/home/ben/PycharmProjects/wizfs/eggs/celery-3.1.17-py2.7.egg/celery/app/base.py", line 629, in conf
Mar 02 12:18:58 san celery[12104]: return self._get_config()
Mar 02 12:18:58 san celery[12104]: File "/home/ben/PycharmProjects/wizfs/eggs/celery-3.1.17-py2.7.egg/celery/app/base.py", line 453, in _get_config
Mar 02 12:18:58 san celery[12104]: self.loader.config_from_object(self._config_source)
Mar 02 12:18:58 san celery[12104]: File "/home/ben/PycharmProjects/wizfs/eggs/celery-3.1.17-py2.7.egg/celery/loaders/base.py", line 145, in config_from_object
Mar 02 12:18:58 san celery[12104]: self._conf = force_mapping(obj)
Mar 02 12:18:58 san celery[12104]: File "/home/ben/PycharmProjects/wizfs/eggs/celery-3.1.17-py2.7.egg/celery/datastructures.py", line 52, in force_mapping
Mar 02 12:18:58 san celery[12104]: return DictAttribute(m) if not isinstance(m, Mapping) else m
Mar 02 12:18:58 san celery[12104]: File "/home/ben/PycharmProjects/wizfs/lib/python2.7/abc.py", line 131, in __instancecheck__
Mar 02 12:18:58 san celery[12104]: subclass = getattr(instance, '__class__', None)
Mar 02 12:18:58 san celery[12104]: File "/home/ben/PycharmProjects/wizfs/eggs/Django-1.7.5-py2.7.egg/django/utils/functional.py", line 224, in inner
Mar 02 12:18:58 san celery[12104]: self._setup()
Mar 02 12:18:58 san celery[12104]: File "/home/ben/PycharmProjects/wizfs/eggs/Django-1.7.5-py2.7.egg/django/conf/__init__.py", line 42, in _setup
Mar 02 12:18:58 san celery[12104]: self._wrapped = Settings(settings_module)
Mar 02 12:18:58 san celery[12104]: File "/home/ben/PycharmProjects/wizfs/eggs/Django-1.7.5-py2.7.egg/django/conf/__init__.py", line 115, in __init__
Mar 02 12:18:58 san celery[12104]: raise ImproperlyConfigured("The SECRET_KEY setting must not be empty.")
Mar 02 12:18:58 san celery[12104]: django.core.exceptions.ImproperlyConfigured: The SECRET_KEY setting must not be empty.
Mar 02 12:18:58 san systemd[1]: celery.service: main process exited, code=exited, status=1/FAILURE
Mar 02 12:18:58 san systemd[1]: Unit celery.service entered failed state.
Mar 02 12:18:58 san systemd[1]: celery.service failed.
```

**Comment by wengole** [comment]
Ok, so I've just tested latest master, and it's fixed whatever issue I was having.

**Comment by joshourisman** [comment]
Using the new late_binding kwarg should fix it:

```
class Common(Configuration):
  VALUE1 = values.Value()

class Local(Common):
  ...

class Production(Common):
  MY_VALUE = values.SecretValue(late_binding=True)
```

**Comment by bittner** [comment]
This issue seems to be fixed. Use the `late_binding` keyword argument.
